import{a as l,S as d,i as c}from"./assets/vendor-CLNDzgXJ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();function m(o){const t={key:"51701755-afeeef66c15ff24568cee0a11",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return l.create({baseURL:"https://pixabay.com/api/",params:t}).get().then(s=>s.data).catch(s=>console.log(s))}const a={formELem:document.querySelector(".form"),imagesList:document.querySelector(".gallery")},u=new d(".img-card a");function f({webformatURL:o,largeImageURL:t,tags:i,likes:s,views:e,comments:r,downloads:n}){return`<li class="img-card">
    <a href="${t}">
    <img src="${o}" alt="${i}">
    </a>
    <ul class="card-text">
    <li class="card-content"><p class="card-content-title">Likes</p><p>${s}</p></li>
    <li class="card-content"><p class="card-content-title">Views</p><p>${e}</p></li>
    <li class="card-content"><p class="card-content-title">Comments</p><p>${r}</p></li>
    <li class="card-content"><p class="card-content-title">Downloads</p><p>${n}</p></li>    
    </ul>
    </li>`}function p(o){const t=o.map(f).join("");a.imagesList.innerHTML=t,u.refresh()}function g(){a.imagesList.innerHTML=""}function h(){a.imagesList.insertAdjacentHTML("afterbegin",'<div class="loader-container"><span class="loader"></span></div>'),document.addEventListener("iziToast-closing",()=>{document.querySelectorAll(".loader-container").forEach(t=>t.remove())})}a.formELem.addEventListener("submit",y);function y(o){o.preventDefault(),g(),h();const t=o.target.elements.searchText.value.trim();if(t===""){c.info({message:"Please enter search words",position:"topRight"});return}m(t).then(i=>{const s=i.hits;s.length===0?c.error({title:"Nothing found!",message:`Sorry, there are no images matching your search "${t}". Please try again!`,position:"topRight"}):(p(s),o.target.reset())})}
//# sourceMappingURL=index.js.map
